# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d7719f7387637ac2e893e4f0d7834a458c14e8586960b751c92c7d9b3efd259decbc22383cf36062e01b16d3ddec3763beedd5c8ae1c5d25a2468fbb0784b3b

test:
  secret_key_base: 3894a12b5ca5dd4e0329c1dc377daed1de3a4a1786dad5f48e72fa134dbf34a45a7553db306e70f76917074d93e4ea0264ff88cfea4900b9e400979dbe3888e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
